server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    #registerWithEureka：false和fetchRegistry：false表明自己是一个eureka server
    redisterWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/